/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LogInController;
import Model.Account;
import Model.LogIn;
import javax.swing.JOptionPane;

/**
 *
 * @author this pc
 */
public class LogInFrm extends javax.swing.JFrame {
    private LogIn loginObj = LogIn.getInstance();
    
    public LogInFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInTitle1 = new javax.swing.JLabel();
        logInUsernameLable1 = new javax.swing.JLabel();
        logInPwdLable1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        loginPwd = new javax.swing.JTextPane();
        logInBtn1 = new javax.swing.JButton();
        logInIsRemember1 = new javax.swing.JCheckBox();
        logInForgetPwd1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        loginUsername = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LogInTitle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogInTitle1.setText("Log In");

        logInUsernameLable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logInUsernameLable1.setText("Username:");

        logInPwdLable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logInPwdLable1.setText("Password:");

        jScrollPane3.setViewportView(loginPwd);

        logInBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logInBtn1.setText("LOGIN");
        logInBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtn1ActionPerformed(evt);
            }
        });

        logInIsRemember1.setText("Remember Me");

        logInForgetPwd1.setText("Forget Password?");
        logInForgetPwd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jScrollPane4.setViewportView(loginUsername);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(LogInTitle1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(logInPwdLable1)
                                    .addComponent(logInUsernameLable1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(logInIsRemember1)
                                .addGap(80, 80, 80)
                                .addComponent(logInBtn1)
                                .addGap(90, 90, 90)
                                .addComponent(logInForgetPwd1)))))
                .addGap(232, 232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogInTitle1)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logInUsernameLable1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logInPwdLable1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logInForgetPwd1)
                            .addComponent(logInBtn1)
                            .addComponent(logInIsRemember1))
                        .addGap(13, 13, 13)))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtn1ActionPerformed
        // TODO add your handling code here:
//        check whether user has fill in all fields or not.
        if (loginPwd.getText().isEmpty() || loginUsername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields!");
        }else {
            String accUsername = loginUsername.getText();
            String accPwd = loginPwd.getText();
            Account acc = LogInController.check(accUsername, accPwd);
            if (acc != null) {
                loginObj.setAccount(acc);
                this.dispose();
            }else {
                int option = JOptionPane.showConfirmDialog(null, "Tài khoản không tồn tại. Bạn có muốn tiếp tục?");
                if (option == JOptionPane.NO_OPTION) this.dispose();
            };
        }
    }//GEN-LAST:event_logInBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new LogInFrm().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogInTitle1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton logInBtn1;
    private javax.swing.JLabel logInForgetPwd1;
    private javax.swing.JCheckBox logInIsRemember1;
    private javax.swing.JLabel logInPwdLable1;
    private javax.swing.JLabel logInUsernameLable1;
    private javax.swing.JTextPane loginPwd;
    private javax.swing.JTextPane loginUsername;
    // End of variables declaration//GEN-END:variables

    private void exit(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
