/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Account;
import Model.LogIn;
import javax.swing.JOptionPane;

/**
 *
 * @author this pc
 */
public class Main extends javax.swing.JFrame {
    private LogIn loginObj = LogIn.getInstance();
    private Account acc = loginObj.getAccount();
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainLogInBtn = new javax.swing.JButton();
        deliveriesMngBtn = new javax.swing.JButton();
        mainDealerMngBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Welcome to our Management System");

        mainLogInBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainLogInBtn.setText("Log In");
        mainLogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLogInBtnActionPerformed(evt);
            }
        });

        deliveriesMngBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deliveriesMngBtn.setText("Deliveries Management");
        deliveriesMngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveriesMngBtnActionPerformed(evt);
            }
        });

        mainDealerMngBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mainDealerMngBtn.setText("Dealer Management");
        mainDealerMngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainDealerMngBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(mainDealerMngBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deliveriesMngBtn)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mainLogInBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveriesMngBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainDealerMngBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(mainLogInBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainLogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainLogInBtnActionPerformed
        // TODO add your handling code here:
        new LogInFrm().setVisible(true);
    }//GEN-LAST:event_mainLogInBtnActionPerformed

    private void deliveriesMngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveriesMngBtnActionPerformed
        // TODO add your handling code here:
        acc = loginObj.getAccount();
        if (acc == null)
            JOptionPane.showMessageDialog(null, "Please Login first to use this function.");
        else if (acc.getRole().equalsIgnoreCase("ACC-002")) {
            new DeliveriesFrm().setVisible(true);
            
        }else {
            JOptionPane.showMessageDialog(null, "Your Account role is unable to user this function");
        }
    }//GEN-LAST:event_deliveriesMngBtnActionPerformed

    private void mainDealerMngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainDealerMngBtnActionPerformed
        // TODO add your handling code here:
//        Check whether user has log in or not
        acc = loginObj.getAccount();
        if (acc == null)
            JOptionPane.showMessageDialog(null, "Please Login first to use this function.");
        else if (acc.getRole().equalsIgnoreCase("ACC-001")) {
            new DealerMngFrm().setVisible(true);
            
        }else {
            JOptionPane.showMessageDialog(null, "Your Account role is unable to user this function");
        }
    }//GEN-LAST:event_mainDealerMngBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        new Main().setVisible(true); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deliveriesMngBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mainDealerMngBtn;
    private javax.swing.JButton mainLogInBtn;
    // End of variables declaration//GEN-END:variables
}
