/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author this pc
 */
public class SearchDealerFrm extends javax.swing.JFrame {

    /**
     * Creates new form SearchDealerFrm
     */
    public SearchDealerFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBackBtn = new javax.swing.JButton();
        SearchDealerTitle = new javax.swing.JLabel();
        searchDealerIDLable = new javax.swing.JLabel();
        searchDealerPhone = new javax.swing.JTextField();
        searchDealerAddr = new javax.swing.JTextField();
        searchNameLable = new javax.swing.JLabel();
        searchDealerAddrLable = new javax.swing.JLabel();
        searchDealerName = new javax.swing.JTextField();
        searchDealerContinuingLable = new javax.swing.JLabel();
        searchDealerPhoneLable = new javax.swing.JLabel();
        searchDealerSubTitle = new javax.swing.JLabel();
        searchDealerID = new javax.swing.JTextField();
        searchDealerBtn = new javax.swing.JButton();
        searchDealerContinuing = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchBackBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchBackBtn.setText("Back");
        searchBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBackBtnActionPerformed(evt);
            }
        });

        SearchDealerTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SearchDealerTitle.setText("Search Dealer's Information");

        searchDealerIDLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchDealerIDLable.setText("Enter Dealer's ID:");

        searchNameLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchNameLable.setText("Dealer's name:");

        searchDealerAddrLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchDealerAddrLable.setText("Dealer's address:");

        searchDealerContinuingLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchDealerContinuingLable.setText("Continuing:");

        searchDealerPhoneLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchDealerPhoneLable.setText("Dealer's phone number:");

        searchDealerSubTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchDealerSubTitle.setText("Dealer's Information");

        searchDealerBtn.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchDealerPhoneLable)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchDealerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(searchNameLable)
                                            .addComponent(searchDealerContinuingLable)))
                                    .addComponent(searchDealerSubTitle))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchDealerName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchDealerContinuing, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(searchBackBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(searchDealerAddrLable)
                                .addGap(18, 18, 18)
                                .addComponent(searchDealerAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(429, 429, 429)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SearchDealerTitle)
                                .addGap(267, 267, 267))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(searchDealerIDLable)
                                .addGap(37, 37, 37)
                                .addComponent(searchDealerID, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(searchDealerBtn)
                                .addGap(125, 125, 125))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchDealerTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDealerID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDealerIDLable)
                    .addComponent(searchDealerBtn))
                .addGap(69, 69, 69)
                .addComponent(searchDealerSubTitle)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDealerAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchNameLable)
                    .addComponent(searchDealerAddrLable)
                    .addComponent(searchDealerName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDealerPhoneLable)
                    .addComponent(searchDealerContinuingLable)
                    .addComponent(searchDealerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDealerContinuing, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(searchBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchDealerFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchDealerFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchDealerFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchDealerFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchDealerFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SearchDealerTitle;
    private javax.swing.JButton searchBackBtn;
    private javax.swing.JTextField searchDealerAddr;
    private javax.swing.JLabel searchDealerAddrLable;
    private javax.swing.JButton searchDealerBtn;
    private javax.swing.JTextField searchDealerContinuing;
    private javax.swing.JLabel searchDealerContinuingLable;
    private javax.swing.JTextField searchDealerID;
    private javax.swing.JLabel searchDealerIDLable;
    private javax.swing.JTextField searchDealerName;
    private javax.swing.JTextField searchDealerPhone;
    private javax.swing.JLabel searchDealerPhoneLable;
    private javax.swing.JLabel searchDealerSubTitle;
    private javax.swing.JLabel searchNameLable;
    // End of variables declaration//GEN-END:variables
}
